[package]
name = "salieri"
version = "0.1.0"
authors = ["Mark Humphreys <mark@mrlhumphreys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "salieri"
path = "src/main.rs"

[dependencies]
actix-web = "4.5.1"
actix-rt = "2.9"
actix-cors = "0.7.0"
rand = "0.8"
bytes = "1.2"
regex = "1.6"

